# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3747d083e47d7439913160e2c2cc86d22ac35a06c4bba57617283fa67e415b802c55659a220b7cc609dea6c3edd1f2481b2983b901afb09d715db364fd192514

test:
  secret_key_base: c30785dee5d07326dff672d602bf375104178c21af95174d90be02db36d00468bffd2f47290f1a1f4efc04cba698d6290aec53e76f17fbd9e3bb237aa1caa95a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
